### ISSUE TITLE
Let's do this

### ISSUE THREAD

**Issue by jnbek** [jantman/arch-autorepo#1]
I'm also searching for a solution here... I been looking at gitlab and jenkins, but I'm not all too keen on how to begin. I maintain nearly 900 AUR packages and would love to automate alot of this process.

**Comment by jnbek** [comment]
So initial tests suggest that if Jenkins is running on an Arch Linux host that makepkg will work. Really just a matter of setting up a Perl script that iterates either the maintainer's package list directly from the AUR ( or a local path tree with each of the git repos ) and unpacks (not necessary for local filesystem git roots), chdir's to where the PKGBUILD lives and runs makepkg, if an all for one one for all way of doing it is desired... or... on a per package basis, use like https://metacpan.org/pod/Jenkins::API to 'create' a new job if a new package is added to a local filesystem. (I'm very much a Perl guy, so I speak Perl :D ) It'll obviously be a trial by fire, a problem arises if/when new dependencies are introduced that a) Don't yet exist on the AUR or b) aren't yet installed on the build server... these will trigger a build failure on Jenkins; Fail point "a" being desirable, but for case b, it'd be nice to have the build system install it, though.... Jenkins requires a lot of TLC to do root operations.

**Comment by jantman** [comment]
@jnbek cool! I'd more or less forgotten about this, and gotten caught up with other things. I only have about a dozen AUR packages that I build (I don't maintain, just build locally for myself), so it's not a big pain, but I automate things for a living and hate having to do it manually.

One thought I had on this, is that since AUR switched to git, it's not terribly difficult to pull in/build AUR packages at a specific commit hash if you don't have local modifications.

Perl is probably my weakest language :(

There's probably no need to create a Jenkins job specific to each package, that could be passed in as parameters to the job. However, I was really thinking of this as living on its own, outside something like Jenkins - I only have one Arch linux box, and only build packages for myself, so I really don't want to have to run a full Jenkins instance just for that.

Honestly, I doubt I'm going to get around to making anything happen with this terribly soon. I have 2 other projects that need my attention... it's possible I might be able to whip up something quickly, essentially a script to do all this (and I guess a Vagrant basebox for the VM stuff), but it's as likely as I'd like it to be.

On the other hand, it seems to me that something which is reusable - and, if anyone was so inclined, could be provided as a hosted solution - would be useful to the community. A lot of other distros have "build services", and while I appreciate the security aspect of building AUR packages locally, it _is_ a bit of a pain...

Re: installing the package, if this were for testing purposes, I'd rather see that done in a VM.

**Comment by jnbek** [comment]
hrm, ok... I have a few irons in the fire, so to speak, to help automate things. I'm going to make it as platform agnostic as possible, so if one wants to run a VM/Docker/Jenkins what not, great. just put the utility in place and go. I'll contact you as I get things done, in the end, I'd love to get something up for hosting resulting packages, but that's another thing for another time :D I'll be in touch.

**Comment by jantman** [comment]
Cool, thanks. I really wish I could commit more time to this, but it's just not going to happen in the near future.

**Comment by jantman** [comment]
@jnbek I think I might be doing some work on this, as I just did a fresh install on my new work laptop and had to rebuild about 20 AUR packages. I've updated the readme with my current plan.
